project_id = "onbxoflsgrwdszjltnge"

[functions.sipgate-api]
verify_jwt = false

[functions.sipgate-webhook]
verify_jwt = false

[functions.generate-offer-pdf]
verify_jwt = false

[functions.email-consent-request]
verify_jwt = false

[functions.email-consent-action]
verify_jwt = false

[functions.stripe-subscription-webhook]
verify_jwt = false
