
-- Batch 3: Advanced courses - Chain-of-Thought, Custom GPTs, Social Media, E-Mail, Strukturogramm, Angebote, KI-Workflows, KI-Agenten, Fortgeschrittene Verkaufstechniken

-- Chain-of-Thought Prompting module lessons
UPDATE lessons SET meta = '{"content_html": "<h2>Chain-of-Thought Prompting</h2><h3>Was ist CoT?</h3><p>Chain-of-Thought (CoT) fordert die KI auf, ihre Denkschritte offenzulegen – das verbessert die Ergebnisqualität bei komplexen Aufgaben dramatisch.</p><h3>Grundtechnik</h3><pre>Löse dieses Problem Schritt für Schritt:\n[Problem]\n\nZeige jeden Denkschritt.\nPrüfe am Ende, ob das Ergebnis logisch ist.</pre><h3>Business-Anwendungen</h3><ul><li><b>Preiskalkulation:</b> Kosten aufschlüsseln → Marge berechnen → Preis festlegen</li><li><b>Vertragsanalyse:</b> Klauseln identifizieren → Risiken bewerten → Empfehlung geben</li><li><b>Marktanalyse:</b> Daten sammeln → Trends erkennen → Strategie ableiten</li></ul>"}'::jsonb WHERE id = 'd47df076-4075-4d08-b44e-6159ecc6d143' AND meta::text = '{}';

-- Few-Shot & Multi-Shot
UPDATE lessons SET meta = '{"content_html": "<h2>Few-Shot & Multi-Shot Prompting</h2><h3>Prinzip</h3><p>Zeige der KI 2-5 Beispiele für das gewünschte Ergebnis, bevor du die eigentliche Aufgabe stellst.</p><h3>Few-Shot Beispiel: E-Mail-Ton</h3><pre>Hier sind Beispiele unseres E-Mail-Stils:\n\nBeispiel 1:\n\"Hallo Herr Müller, vielen Dank für Ihr Interesse an...\"\n\nBeispiel 2:\n\"Liebe Frau Schmidt, wir freuen uns über Ihre Anfrage...\"\n\nSchreibe jetzt eine E-Mail an:\nHerr Weber, Anfrage zu unserem Premium-Paket.</pre><h3>Multi-Shot: Konsistente Outputs</h3><pre>Hier sind 3 Beispiele für LinkedIn-Posts in unserem Stil:\n[Post 1]\n[Post 2]\n[Post 3]\n\nSchreibe jetzt einen Post zum Thema [X] im gleichen Stil.\nBehalte bei: Länge, Tonalität, Emoji-Nutzung, CTA-Art.</pre><h3>Wann nutzen?</h3><ul><li>Markenstimme beibehalten</li><li>Konsistente Formatierung</li><li>Spezifischen Output-Stil erzwingen</li></ul>"}'::jsonb WHERE id = 'c9770b0c-fa30-4037-b01f-fefe3c95f963';

-- Custom GPTs erstellen
UPDATE lessons SET meta = '{"content_html": "<h2>Custom GPTs erstellen</h2><h3>Was sind Custom GPTs?</h3><p>Maßgeschneiderte KI-Assistenten mit eigenem Wissen, Persönlichkeit und Fähigkeiten.</p><h3>Anwendungsfälle</h3><ul><li><b>Sales-GPT:</b> Kennt dein Produkt, beantwortet Kundenfragen</li><li><b>Onboarding-GPT:</b> Führt neue Mitarbeiter ein</li><li><b>Support-GPT:</b> Beantwortet häufige Fragen</li><li><b>Content-GPT:</b> Erstellt Inhalte in deiner Markenstimme</li></ul><h3>Aufbau eines GPTs</h3><ol><li><b>Name & Beschreibung:</b> Klar und spezifisch</li><li><b>Instructions:</b> System-Prompt mit Verhalten, Grenzen, Stil</li><li><b>Knowledge:</b> PDFs, Dokumente, Datenbanken hochladen</li><li><b>Actions:</b> API-Verbindungen (optional)</li><li><b>Conversation Starters:</b> Vorschläge für den Start</li></ol>"}'::jsonb WHERE id = 'd7f5f035-1467-49f3-810f-2d182186789b' AND meta::text = '{}';

-- API-Prompt-Optimierung
UPDATE lessons SET meta = '{"content_html": "<h2>API-Prompt-Optimierung</h2><h3>API vs. Chat-Interface</h3><table><tr><th>Aspekt</th><th>Chat</th><th>API</th></tr><tr><td>Einsatz</td><td>Manuell</td><td>Automatisiert</td></tr><tr><td>Skalierung</td><td>1 Anfrage</td><td>Tausende/Stunde</td></tr><tr><td>Konsistenz</td><td>Variiert</td><td>Kontrolliert (Temperature)</td></tr><tr><td>Kosten</td><td>Abo-Preis</td><td>Pay-per-Token</td></tr></table><h3>API-Prompt Best Practices</h3><pre>// System Prompt (einmal setzen)\n{\n  \"role\": \"system\",\n  \"content\": \"Du bist ein Lead-Scoring-System. Antworte NUR mit validem JSON. Keine Erklärungen.\"\n}\n\n// User Prompt (pro Anfrage)\n{\n  \"role\": \"user\",\n  \"content\": \"Bewerte: {{lead_data}}\"\n}</pre><h3>Kosten optimieren</h3><ul><li>Kurze, präzise Prompts = weniger Token = günstiger</li><li>Temperature 0 für konsistente Ergebnisse</li><li>Kleinere Modelle für einfache Aufgaben (GPT-4-mini statt GPT-4)</li><li>Caching für identische Anfragen</li></ul>"}'::jsonb WHERE id = 'cbed9a57-6e2b-4d43-ab62-30f5c143d27c';

-- Content-Kalender mit KI
UPDATE lessons SET meta = '{"content_html": "<h2>Content-Kalender mit KI</h2><h3>Monatliche Content-Planung</h3><pre>Erstelle einen Content-Kalender für [Monat]:\n\nBranche: [X]\nZielgruppe: [Y]\nKanäle: LinkedIn, Instagram, Newsletter\n\nPro Woche:\n- Mo: LinkedIn-Post (Thought Leadership)\n- Mi: Instagram Reel/Carousel\n- Fr: LinkedIn-Post (Case Study/Tipp)\n- 2x/Mo: Newsletter\n\nPro Eintrag: Thema, Format, Hook, CTA, Hashtags</pre><h3>Content-Recycling Prompt</h3><pre>Verwandle diesen Blogartikel:\n[Artikel]\n\nIn:\n1. 3 LinkedIn-Posts\n2. 5 Instagram-Captions\n3. 1 Newsletter-Abschnitt\n4. 10 Twitter/X-Posts\n\nJeweils angepasst an die Plattform.</pre>"}'::jsonb WHERE id = 'd98878b0-e44c-453c-8d85-00815e69b2f5' AND meta::text = '{}';

-- Reels & Kurzvideos
UPDATE lessons SET meta = '{"content_html": "<h2>Reels & Kurzvideos mit KI</h2><h3>Reel-Skript Prompt</h3><pre>Erstelle ein 30-Sekunden Reel-Skript:\n\nThema: [X]\nZielgruppe: [Y]\nZiel: [Views/Leads/Branding]\n\nStruktur:\n- Hook (0-3 Sek): Provokante Frage/Aussage\n- Problem (3-8 Sek): Schmerzpunkt adressieren\n- Lösung (8-22 Sek): 3 Quick-Tipps\n- CTA (22-30 Sek): Was soll der Zuschauer tun?\n\nInkl. Text-Overlays und Musik-Empfehlung.</pre><h3>Batch-Produktion</h3><pre>Erstelle Skripte für 5 Reels zum Thema [X]:\n\nJedes Reel:\n- Anderer Blickwinkel\n- Eigene Hook\n- 30 Sekunden\n- Text-Overlays definiert\n\nNumeriere die Skripte für die Produktion.</pre>"}'::jsonb WHERE id = 'd149cb10-55dc-423b-8bc1-70a72c0f49e9';

-- E-Mail-Sequenzen mit KI
UPDATE lessons SET meta = '{"content_html": "<h2>E-Mail-Sequenzen mit KI</h2><h3>Die perfekte Nurturing-Sequenz</h3><pre>Erstelle eine 7-teilige E-Mail-Nurturing-Sequenz:\n\nZielgruppe: [ICP]\nProdukt: [X]\nZiel: Vom Erstkontakt zum Beratungsgespräch\n\nE-Mail 1 (Tag 0): Willkommen + Quick Win\nE-Mail 2 (Tag 2): Problem vertiefen\nE-Mail 3 (Tag 5): Lösung vorstellen\nE-Mail 4 (Tag 8): Social Proof / Case Study\nE-Mail 5 (Tag 12): FAQ / Einwände entkräften\nE-Mail 6 (Tag 16): Exklusives Angebot\nE-Mail 7 (Tag 21): Letzte Chance\n\nJede E-Mail: Betreff, Preheader, Body (max 150 Wörter), CTA</pre>"}'::jsonb WHERE id = '82ccf6f5-11e3-4873-9a37-1f247c8e0b5f';

-- A/B-Testing mit KI
UPDATE lessons SET meta = '{"content_html": "<h2>A/B-Testing mit KI</h2><h3>Was testen?</h3><ul><li><b>Betreffzeilen:</b> Emotionell vs. sachlich</li><li><b>CTAs:</b> Direkt vs. soft</li><li><b>Tonalität:</b> Du vs. Sie</li><li><b>Länge:</b> Kurz vs. ausführlich</li></ul><h3>A/B-Test Prompt</h3><pre>Erstelle 2 Varianten dieser E-Mail:\n[Original E-Mail]\n\nVariante A: Emotionaler Ansatz\n- Story-basiert\n- Persönliche Ansprache\n- Empathischer Ton\n\nVariante B: Daten-basierter Ansatz\n- Zahlen und Fakten\n- ROI-fokussiert\n- Professioneller Ton\n\nGleicher CTA bei beiden.\nGleiche Länge (±10%).</pre><h3>Ergebnisse interpretieren</h3><pre>Analysiere diese A/B-Test-Ergebnisse:\nVariante A: [Öffnungsrate]%, [Klickrate]%, [Conversion]%\nVariante B: [Öffnungsrate]%, [Klickrate]%, [Conversion]%\n\nStatistisch signifikant?\nWas lernen wir?\nNächster Test-Vorschlag?</pre>"}'::jsonb WHERE id = '6739b1ef-dfc8-45dd-8360-a20d41d5af69' AND meta::text = '{}';

-- Strukturogramm-Analyse
UPDATE lessons SET meta = '{"content_html": "<h2>Strukturogramm-Analyse</h2><h3>Die 3 Grundtypen</h3><ul><li><b>🟢 Grünhirn:</b> Beziehungsorientiert, harmoniebedürftig, empathisch. Kaufentscheidung: Vertrauen & Beziehung.</li><li><b>🔴 Rothirn:</b> Dominant, ergebnisorientiert, schnell. Kaufentscheidung: Ergebnisse & Status.</li><li><b>🔵 Blauhirn:</b> Analytisch, detailorientiert, vorsichtig. Kaufentscheidung: Daten & Fakten.</li></ul><h3>Erkennungsmerkmale</h3><table><tr><th>Signal</th><th>Grün</th><th>Rot</th><th>Blau</th></tr><tr><td>Sprache</td><td>Weich, Fragen</td><td>Direkt, Fordernd</td><td>Präzise, Fachlich</td></tr><tr><td>Tempo</td><td>Langsam</td><td>Schnell</td><td>Methodisch</td></tr><tr><td>E-Mail-Stil</td><td>Lang, persönlich</td><td>Kurz, auf den Punkt</td><td>Detailliert, Fragen</td></tr></table>"}'::jsonb WHERE id = '819a35c5-ff26-47f3-8c0a-422b1168452a' AND meta::text = '{}';

-- Kaufbereitschaft messen
UPDATE lessons SET meta = '{"content_html": "<h2>Kaufbereitschaft messen</h2><h3>Die 5 Kaufsignale</h3><ol><li><b>Preisfragen:</b> \"Was kostet das?\" = hohes Interesse</li><li><b>Detailfragen:</b> \"Wie genau funktioniert...\" = Evaluation</li><li><b>Timing-Fragen:</b> \"Wann könnten wir starten?\" = bereit</li><li><b>Vergleichsfragen:</b> \"Was unterscheidet Sie von...\" = kurz vor Entscheidung</li><li><b>Prozessfragen:</b> \"Wie läuft die Implementierung?\" = mental bereits Kunde</li></ol><h3>KI-Prompt: Kaufbereitschaft analysieren</h3><pre>Analysiere dieses Gesprächstranskript:\n[Transkript]\n\nIdentifiziere:\n1. Kaufsignale (mit Zitat)\n2. Bedenken/Einwände\n3. Kaufbereitschafts-Score (0-100)\n4. Phase im Kaufprozess\n5. Empfohlene nächste Aktion\n\nBegründe deine Einschätzung.</pre>"}'::jsonb WHERE id = '20276c7a-f7e2-437f-a664-11325af51f8e';

-- Angebote mit KI erstellen
UPDATE lessons SET meta = '{"content_html": "<h2>Angebote mit KI erstellen</h2><h3>Der KI-Angebotsprozess</h3><ol><li>Discovery-Daten sammeln</li><li>Schmerzpunkte identifizieren</li><li>Passende Module auswählen</li><li>KI generiert personalisiertes Angebot</li><li>Review und Anpassung</li><li>Versand mit Follow-up-Sequenz</li></ol><h3>Komplett-Prompt</h3><pre>Erstelle ein Angebot:\n\nKunde: [Name, Firma, Branche]\nSchmerzpunkte: [aus Discovery Call]\nBudget-Range: [X-Y EUR]\n\nStruktur:\n1. Persönliche Anrede (Bezug aufs Gespräch)\n2. Problem-Zusammenfassung\n3. Unsere Lösung (3 Module)\n4. Erwartete Ergebnisse (messbar)\n5. Investition (3 Preis-Optionen: Basic/Pro/Premium)\n6. Zeitplan (90 Tage)\n7. Nächste Schritte\n8. Garantie</pre>"}'::jsonb WHERE id = '37d043c2-43d7-4a7e-8e65-6d1cc630a3c1' AND meta::text = '{}';

-- CRM-Workflows automatisieren
UPDATE lessons SET meta = '{"content_html": "<h2>CRM-Workflows automatisieren</h2><h3>Top 5 CRM-Automationen</h3><ol><li><b>Lead-Zuweisung:</b> Neue Leads automatisch dem richtigen Mitarbeiter zuweisen</li><li><b>Follow-up Reminder:</b> Automatische Erinnerung wenn Lead 3 Tage nicht kontaktiert</li><li><b>Status-Updates:</b> Pipeline-Stage automatisch aktualisieren nach Aktionen</li><li><b>E-Mail-Trigger:</b> Sequenz starten wenn Lead Status wechselt</li><li><b>Reporting:</b> Wöchentliche KPI-E-Mail automatisch generieren</li></ol><h3>Webhook-Prompt</h3><pre>Erstelle eine Webhook-Integration:\nTrigger: Neuer Lead in CRM\nPayload: {{lead_json}}\n\nKI soll:\n1. Lead bewerten\n2. Passende E-Mail-Sequenz auswählen\n3. Aufgabe für Mitarbeiter erstellen\n\nAntworte als JSON.</pre>"}'::jsonb WHERE id = 'c9beea3f-aa9f-4470-a653-066f46bfe8f5';

-- E-Mail-Trigger & Webhooks
UPDATE lessons SET meta = '{"content_html": "<h2>E-Mail-Trigger & Webhooks</h2><h3>Trigger-Typen</h3><ul><li><b>Event-basiert:</b> Lead registriert sich, Angebot geöffnet, Zahlung eingeht</li><li><b>Zeitbasiert:</b> X Tage nach Kontakt, Geburtstag, Jubiläum</li><li><b>Verhaltensbasiert:</b> Website besucht, E-Mail geöffnet, Link geklickt</li></ul><h3>Webhook Setup</h3><pre>// Webhook empfängt Lead-Daten\n{\n  \"event\": \"lead.created\",\n  \"data\": {\n    \"name\": \"Max Müller\",\n    \"email\": \"max@firma.de\",\n    \"source\": \"website\"\n  }\n}\n\n// KI verarbeitet und reagiert automatisch</pre><h3>Best Practices</h3><ul><li>Immer Webhook-Signatur validieren</li><li>Retry-Logik für fehlgeschlagene Zustellungen</li><li>Logging für Debugging</li></ul>"}'::jsonb WHERE id = 'ce42509a-7286-44a3-8c70-530671fadf87';

-- KI-Agenten für Business
UPDATE lessons SET meta = '{"content_html": "<h2>KI-Agenten für Business</h2><h3>Was sind KI-Agenten?</h3><p>Autonome KI-Systeme die selbstständig Aufgaben ausführen, Entscheidungen treffen und Workflows orchestrieren.</p><h3>Agent-Typen</h3><ul><li><b>Recherche-Agent:</b> Sammelt und analysiert Informationen</li><li><b>Sales-Agent:</b> Qualifiziert Leads und erstellt Angebote</li><li><b>Support-Agent:</b> Beantwortet Kundenanfragen</li><li><b>Analytics-Agent:</b> Erstellt Reports und Insights</li></ul><h3>Agent-Architektur</h3><pre>1. Perception: Input empfangen\n2. Reasoning: Situation analysieren\n3. Planning: Aktionsplan erstellen\n4. Action: Tools nutzen (APIs, DB, E-Mail)\n5. Reflection: Ergebnis prüfen\n6. Loop: Bei Bedarf wiederholen</pre>"}'::jsonb WHERE id = '88db7fc5-fd3e-455b-85b1-b890f0970797' AND meta::text = '{}';

-- No-Code Automation Grundlagen
UPDATE lessons SET meta = '{"content_html": "<h2>No-Code Automation Grundlagen</h2><h3>Dein erster KI-Workflow</h3><pre>Schritt-für-Schritt:\n1. Make.com Account erstellen\n2. Neues Szenario starten\n3. Trigger: Webhook wählen\n4. Modul: OpenAI hinzufügen\n5. Prompt konfigurieren\n6. Output: CRM-Update oder E-Mail\n7. Testen mit Beispieldaten</pre><h3>Top 3 Starter-Workflows</h3><ol><li>Kontaktformular → KI-Bewertung → CRM</li><li>E-Mail-Eingang → KI-Klassifizierung → Auto-Antwort</li><li>Kalender-Event → KI-Vorbereitung → Briefing-E-Mail</li></ol>"}'::jsonb WHERE id = 'aa110000-0000-0000-0000-000000000009' AND meta::text = '{}';

-- Dein erster KI-Workflow
UPDATE lessons SET meta = '{"content_html": "<h2>Dein erster KI-Workflow</h2><h3>Hands-on Tutorial</h3><ol><li>Öffne Make.com → Neues Szenario</li><li>Füge Webhook-Trigger hinzu</li><li>Teste mit Postman oder curl</li><li>Füge HTTP-Modul für KI-API hinzu</li><li>Konfiguriere den Prompt</li><li>Parse die JSON-Antwort</li><li>Füge Aktion hinzu (E-Mail/Slack/CRM)</li></ol><h3>Troubleshooting</h3><ul><li><b>Keine Antwort:</b> API-Key prüfen</li><li><b>Falsches Format:</b> JSON-Parsing prüfen</li><li><b>Timeout:</b> Prompt kürzen, Modell wechseln</li></ul>"}'::jsonb WHERE id = 'aa110000-0000-0000-0000-000000000010';

-- Lead-Qualifizierung mit KI (Vertrieb)
UPDATE lessons SET meta = '{"content_html": "<h2>Lead-Qualifizierung mit KI</h2><h3>Der KI-gestützte Qualifizierungsprozess</h3><ol><li>Lead kommt rein (Formular, Empfehlung, Prospecting)</li><li>KI bewertet automatisch nach ICP-Kriterien</li><li>Score bestimmt die Priorität und nächste Aktion</li><li>Vertrieb erhält vorbereitetes Briefing</li></ol><h3>Qualifizierungs-Prompt</h3><pre>Qualifiziere diesen Lead:\n[Lead-Daten]\n\nPrüfe:\n1. ICP-Fit (Branche, Größe, Budget)\n2. Kaufbereitschaft (Signale im Text)\n3. Entscheider-Status\n4. Timing (Dringlichkeit)\n\nScore: 0-100\nKategorie: Hot/Warm/Cold\nNächste Aktion: [Empfehlung]</pre>"}'::jsonb WHERE id = 'aa110000-0000-0000-0000-000000000008';

-- Texte mit KI erstellen
UPDATE lessons SET meta = '{"content_html": "<h2>Texte mit KI erstellen</h2><h3>Content-Typen und Prompts</h3><h4>Blog-Artikel</h4><pre>Schreibe einen 800-Wörter Fachartikel:\nThema: [X]\nZielgruppe: [Y]\nSEO-Keyword: [Z]\nFormat: H2/H3, Bullet Points, Fazit+CTA</pre><h4>Produktbeschreibung</h4><pre>Schreibe eine überzeugende Produktbeschreibung:\nProdukt: [X]\nZielgruppe: [Y]\nUSPs: [1,2,3]\nTon: [sachlich/emotional/premium]\n200-300 Wörter</pre><h4>Werbetext</h4><pre>Erstelle 3 Varianten eines Werbetexts:\nProdukt: [X]\nKanal: [Facebook/Google/LinkedIn]\nZiel: [Klick/Lead/Verkauf]\nBudget-Hinweis: [optional]\nJe max 90 Zeichen (Headline) + 150 Zeichen (Body)</pre>"}'::jsonb WHERE id = 'aa110000-0000-0000-0000-000000000005';

-- Fortgeschrittene Verkaufstechniken - Einwandbehandlung
UPDATE lessons SET meta = '{"content_html": "<h2>Die 5 Standard-Einwände</h2><h3>1. \"Zu teuer\"</h3><pre>KI-Prompt: Entkräfte den Preiseinwand:\nProdukt: [X], Preis: [Y]\nArgumentiere mit ROI, Zeitersparnis, Opportunitätskosten.\n3 Formulierungen: empathisch, logisch, provokant.</pre><h3>2. \"Kein Bedarf\"</h3><pre>Der Kunde sagt: \"Wir brauchen das nicht.\"\nUnser Produkt löst: [Problem]\nErstelle 3 Fragen die den versteckten Bedarf aufdecken.</pre><h3>3. \"Keine Zeit\"</h3><pre>Kunde hat keine Zeit für ein Gespräch.\nErstelle:\n- 2-Satz Elevator Pitch\n- 1-Minuten Kurzpräsentation\n- 30-Sekunden Voice-Message Skript</pre><h3>4. \"Muss mit Partner besprechen\"</h3><p>Strategie: Briefing-Dokument für den Partner erstellen lassen.</p><h3>5. \"Haben schon einen Anbieter\"</h3><p>Strategie: Differenzierung und Switching-Kosten transparent machen.</p>"}'::jsonb WHERE id = '8daa506e-b965-48e0-908c-13d65941aa52';

-- KI im Vertriebsprozess
UPDATE lessons SET meta = '{"content_html": "<h2>KI im Vertriebsprozess</h2><h3>Vertriebsphasen + KI</h3><ul><li><b>Prospecting:</b> KI recherchiert potenzielle Kunden</li><li><b>Erstansprache:</b> KI personalisiert Nachrichten</li><li><b>Discovery:</b> KI bereitet Gesprächsleitfaden vor</li><li><b>Analyse:</b> KI wertet Gespräch aus</li><li><b>Angebot:</b> KI generiert maßgeschneidertes Proposal</li><li><b>Follow-up:</b> KI plant automatische Sequenz</li><li><b>Closing:</b> KI empfiehlt optimale Strategie</li></ul>"}'::jsonb WHERE id = 'aa110000-0000-0000-0000-000000000007' AND meta::text = '{}';

-- KI-Workflows in der Praxis
UPDATE lessons SET meta = '{"content_html": "<h2>KI-Workflows in der Praxis</h2><h3>Enterprise-Workflow: Lead-to-Customer</h3><pre>1. Lead Registration Event\n2. → Webhook an Make.com\n3. → KI-Bewertung (Score + Typ)\n4. → CRM-Update (Status + Score)\n5. → Router:\n   a) Hot → Slack-Alert + Sofort-E-Mail\n   b) Warm → Nurturing-Sequenz\n   c) Cold → Monitoring-Liste\n6. → Aufgabe für Vertrieb erstellen\n7. → Activity Log aktualisieren</pre>"}'::jsonb WHERE id = 'aa110000-0000-0000-0000-000000000009' AND meta::text = '{}';
