
-- Batch 1: Fill Prompting Grundlagen & KI-Content Basics lessons

-- Willkommen zur KI-Revolution
UPDATE lessons SET meta = '{"content_html": "<h2>Willkommen zur KI-Revolution</h2><p>Künstliche Intelligenz verändert die Art, wie wir arbeiten – grundlegend und unwiderruflich.</p><h3>Warum jetzt?</h3><ul><li><b>2022:</b> ChatGPT macht KI für alle zugänglich</li><li><b>2023:</b> Claude, Gemini, Midjourney revolutionieren Branchen</li><li><b>2024-25:</b> KI wird zum Standard-Werkzeug im Business</li></ul><h3>Was KI für dich bedeutet</h3><ul><li>80% Zeitersparnis bei Routineaufgaben</li><li>Bessere Entscheidungen durch Datenanalyse</li><li>Skalierung ohne proportional mehr Personal</li><li>Wettbewerbsvorteil gegenüber Nicht-Nutzern</li></ul><h3>Was du in diesem Kurs lernst</h3><ol><li>Was KI ist und wie sie funktioniert</li><li>Wie du KI-Tools effektiv nutzt</li><li>Deine ersten Prompts schreiben</li><li>KI in deinen Arbeitsalltag integrieren</li></ol>"}'::jsonb WHERE id = 'ed11179e-c188-41f4-8209-1802e7a95b93';

-- Wie funktionieren LLMs?
UPDATE lessons SET meta = '{"content_html": "<h2>Wie funktionieren Large Language Models?</h2><h3>Das Prinzip</h3><p>LLMs sind KI-Modelle, die auf Milliarden von Texten trainiert wurden. Sie sagen das wahrscheinlichste nächste Wort voraus.</p><h3>Wichtige Konzepte</h3><dl><dt><b>Token</b></dt><dd>Textbausteine (~4 Zeichen). GPT-4 verarbeitet bis zu 128.000 Token gleichzeitig.</dd><dt><b>Kontext-Fenster</b></dt><dd>Die Menge an Text, die das Modell gleichzeitig \"sehen\" kann.</dd><dt><b>Temperature</b></dt><dd>0 = deterministische Antworten, 1 = kreative/zufällige Antworten</dd><dt><b>System Prompt</b></dt><dd>Versteckte Anweisung, die das Verhalten grundlegend steuert</dd></dl><h3>Stärken</h3><ul><li>Texterstellung und -analyse</li><li>Zusammenfassungen und Übersetzungen</li><li>Brainstorming und Ideenfindung</li><li>Code generieren und erklären</li></ul><h3>Grenzen</h3><ul><li>Können halluzinieren (falsche Fakten erfinden)</li><li>Wissen hat ein Stichtag</li><li>Keine echte Intelligenz oder Verständnis</li><li>Sensible Daten nie ungefiltert eingeben!</li></ul>"}'::jsonb WHERE id = '4404e035-e2c5-4518-934d-e4b0776cdf7d';

-- Quiz: KI-Grundlagen
UPDATE lessons SET meta = '{"content_html": "<h2>Quiz: KI-Grundlagen</h2><h3>Frage 1</h3><p>Was ist ein Token?</p><ul><li>a) Ein Passwort für KI-Tools</li><li>b) Eine Texteinheit (~4 Zeichen), die das Modell verarbeitet ✅</li><li>c) Eine Kryptowährung</li></ul><h3>Frage 2</h3><p>Was passiert bei Temperature = 0?</p><ul><li>a) Das Modell gibt kreativere Antworten</li><li>b) Das Modell gibt konsistentere, deterministische Antworten ✅</li><li>c) Das Modell stoppt</li></ul><h3>Frage 3</h3><p>Was ist eine \"Halluzination\"?</p><ul><li>a) Wenn die KI Bilder generiert</li><li>b) Wenn die KI überzeugend klingende, aber falsche Infos generiert ✅</li><li>c) Wenn die KI abstürzt</li></ul><h3>Frage 4</h3><p>Wofür steht LLM?</p><ul><li>a) Large Language Model ✅</li><li>b) Low Latency Machine</li><li>c) Linear Learning Method</li></ul><h3>Frage 5</h3><p>Was solltest du NIE in einen KI-Prompt eingeben?</p><ul><li>a) Kreative Textanfragen</li><li>b) Sensible personenbezogene Daten ohne Einwilligung ✅</li><li>c) Lange Texte zum Zusammenfassen</li></ul>"}'::jsonb WHERE id = '75fbb8e0-df34-418e-aed3-4ba2f8f667fc';

-- Die Anatomie eines Prompts
UPDATE lessons SET meta = '{"content_html": "<h2>Die Anatomie eines guten Prompts</h2><h3>Die 4 Bausteine</h3><ol><li><b>Rolle:</b> Wer soll die KI sein?<br/><i>\"Du bist ein erfahrener Marketing-Experte für den Mittelstand.\"</i></li><li><b>Kontext:</b> Hintergrund-Infos<br/><i>\"Mein Unternehmen ist ein Handwerksbetrieb mit 15 Mitarbeitern.\"</i></li><li><b>Aufgabe:</b> Was genau soll getan werden?<br/><i>\"Erstelle 5 LinkedIn-Post-Ideen zum Thema Mitarbeitergewinnung.\"</i></li><li><b>Format:</b> Wie soll das Ergebnis aussehen?<br/><i>\"Jeder Post: Hook (1 Satz) + Haupttext (3 Sätze) + CTA\"</i></li></ol><h3>Beispiel: Kompletter Prompt</h3><pre>Du bist ein erfahrener Marketing-Experte für den Mittelstand.\n\nMein Unternehmen ist ein Handwerksbetrieb mit 15 Mitarbeitern\nim Bereich Sanitär/Heizung.\n\nErstelle 5 LinkedIn-Post-Ideen zum Thema Mitarbeitergewinnung.\n\nFormat pro Post:\n- Hook (1 provokanter Satz)\n- Haupttext (3-4 Sätze)\n- CTA (Frage an die Community)\n- 3 Hashtags</pre><h3>Pro-Tipps</h3><ul><li>Je spezifischer, desto besser</li><li>Gib Beispiele für gewünschten Stil</li><li>Iteriere: Verfeinere die Antwort mit Folgeprompts</li></ul>"}'::jsonb WHERE id = 'f1e93197-d078-45ed-9a0e-01e0d14b3ad8';

-- Praxis: Erste Prompts schreiben
UPDATE lessons SET meta = '{"content_html": "<h2>Praxis: Deine ersten 5 Business-Prompts</h2><h3>Aufgabe 1: Kunden-E-Mail</h3><p>Schreibe einen Prompt, der eine professionelle Antwort auf eine Kundenanfrage generiert.</p><pre>Vorlage:\nDu bist Kundenberater bei [Firma].\nKundenanfrage: [Text]\nAntworte professionell in max. 100 Wörtern.\nBiete konkreten nächsten Schritt an.</pre><h3>Aufgabe 2: Social Media</h3><p>Erstelle einen Prompt für einen LinkedIn-Post über dein Fachgebiet.</p><h3>Aufgabe 3: Meeting-Vorbereitung</h3><p>Prompt für eine Agenda mit 5 Gesprächspunkten.</p><h3>Aufgabe 4: Wettbewerber-Analyse</h3><p>Prompt für eine SWOT-Analyse deines Marktes.</p><h3>Aufgabe 5: Stellenanzeige</h3><p>Prompt für eine ansprechende Stellenanzeige in deiner Branche.</p><p><b>Bewertungskriterien:</b></p><ul><li>Enthält der Prompt eine Rolle?</li><li>Ist genug Kontext gegeben?</li><li>Ist die Aufgabe spezifisch?</li><li>Ist das gewünschte Format definiert?</li></ul>"}'::jsonb WHERE id = 'a93f264e-8223-47e9-828f-d4ce225c57c1';

-- Die KI-Tool-Landschaft 2025
UPDATE lessons SET meta = '{"content_html": "<h2>KI-Tool-Landschaft 2025</h2><h3>Text-KI</h3><ul><li><b>ChatGPT (OpenAI)</b> – Allrounder, stärkstes Ökosystem</li><li><b>Claude (Anthropic)</b> – Beste Textanalyse, sicherster Output</li><li><b>Gemini (Google)</b> – Integration in Google-Produkte, großes Kontextfenster</li></ul><h3>Bild-KI</h3><ul><li><b>Midjourney</b> – Höchste Bildqualität</li><li><b>DALL-E 3</b> – In ChatGPT integriert</li><li><b>Stable Diffusion</b> – Open Source, lokal nutzbar</li></ul><h3>Video-KI</h3><ul><li><b>Sora (OpenAI)</b> – Text-zu-Video</li><li><b>Runway</b> – Videoschnitt mit KI</li><li><b>HeyGen</b> – KI-Avatare für Videos</li></ul><h3>Produktivitäts-KI</h3><ul><li><b>Notion AI</b> – Dokumentation & Wissen</li><li><b>Otter.ai</b> – Meeting-Transkription</li><li><b>Perplexity</b> – KI-gestützte Recherche</li></ul><h3>Empfehlung: Starter-Stack</h3><ol><li>ChatGPT Plus (20$/Mo) für Texte</li><li>Perplexity für Recherche</li><li>Canva AI für Design</li></ol>"}'::jsonb WHERE id = '17335c04-5600-4bf3-9923-d54917f57eb8';

-- ChatGPT vs. Claude vs. Gemini
UPDATE lessons SET meta = '{"content_html": "<h2>ChatGPT vs. Claude vs. Gemini</h2><h3>Detailvergleich</h3><table><tr><th>Feature</th><th>ChatGPT</th><th>Claude</th><th>Gemini</th></tr><tr><td>Texterstellung</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td></tr><tr><td>Datenanalyse</td><td>⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td></tr><tr><td>Kontextfenster</td><td>128K</td><td>200K</td><td>1M+</td></tr><tr><td>Code</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td></tr><tr><td>Custom GPTs</td><td>✅</td><td>❌</td><td>✅ (Gems)</td></tr><tr><td>Bildgenerierung</td><td>✅ DALL-E</td><td>❌</td><td>✅ Imagen</td></tr><tr><td>Preis/Monat</td><td>20$</td><td>20$</td><td>20$</td></tr></table><h3>Wann welches Tool?</h3><ul><li><b>ChatGPT:</b> Allrounder, Marketing, Custom GPTs bauen</li><li><b>Claude:</b> Lange Dokumente analysieren, sicherste Outputs, Code</li><li><b>Gemini:</b> Google-Integration, sehr lange Texte, multimodal</li></ul><h3>Pro-Tipp</h3><p>Nutze alle drei! Jedes Tool hat seine Stärken. Vergleiche die Ergebnisse bei wichtigen Aufgaben.</p>"}'::jsonb WHERE id = 'b91a76e3-0192-4854-a7ed-43d136ddafd0';

-- Blogartikel in 10 Minuten
UPDATE lessons SET meta = '{"content_html": "<h2>Blogartikel in 10 Minuten mit KI</h2><h3>Schritt-für-Schritt Anleitung</h3><h4>Minute 1-2: Thema & Keyword</h4><pre>Ich schreibe für [Branche/Zielgruppe].\nSchlage 5 Blog-Themen vor, die:\n- Ein konkretes Problem lösen\n- Suchvolumen haben\n- Unsere Expertise zeigen\nMit je einem Haupt-Keyword.</pre><h4>Minute 3-4: Gliederung</h4><pre>Erstelle eine SEO-optimierte Gliederung:\nThema: [X]\nKeyword: [Y]\nZielgruppe: [Z]\n\nStruktur:\n- H1: Titel mit Keyword\n- H2: 4-5 Hauptabschnitte\n- H3: je 2-3 Unterpunkte\n- Fazit mit CTA</pre><h4>Minute 5-8: Text generieren</h4><pre>Schreibe den Artikel nach dieser Gliederung:\n[Gliederung einfügen]\n\n800-1000 Wörter.\nStil: Praxisnah, mit Beispielen.\nSEO: Keyword natürlich 3-5x einbauen.\nFormat: Bullet Points, kurze Absätze.</pre><h4>Minute 9-10: Optimierung</h4><pre>Optimiere diesen Artikel:\n[Text]\n- Meta-Description (max 160 Zeichen)\n- 3 alternative Titel\n- Social-Media-Teaser (2 Sätze)\n- 5 interne Verlinkungsvorschläge</pre>"}'::jsonb WHERE id = 'fb9efde0-8720-474c-93b9-abebc82d50ae';

-- E-Mail-Texte die konvertieren
UPDATE lessons SET meta = '{"content_html": "<h2>E-Mail-Texte die konvertieren</h2><h3>Die AIDA-Formel für E-Mails</h3><ul><li><b>A</b>ttention: Betreffzeile die öffnet</li><li><b>I</b>nterest: Erster Satz fesselt</li><li><b>D</b>esire: Nutzen klar machen</li><li><b>A</b>ction: Klarer CTA</li></ul><h3>Prompt: Betreffzeilen</h3><pre>Erstelle 10 E-Mail-Betreffzeilen für:\nAnlass: [Newsletter/Follow-up/Angebot]\nZielgruppe: [X]\nZiel: [Öffnungsrate maximieren]\n\nRegeln:\n- Max 50 Zeichen\n- Neugier wecken\n- Personalisierung nutzen\n- Keine Spam-Wörter</pre><h3>Prompt: Komplette E-Mail</h3><pre>Schreibe eine [Typ]-E-Mail:\nAbsender: [Firma/Person]\nEmpfänger: [Zielgruppe]\nAnlass: [X]\nZiel: [Termin/Kauf/Download]\n\nFormat:\n- Persönliche Anrede\n- 1 Satz Bezug (Kontext)\n- 2-3 Sätze Mehrwert\n- 1 klarer CTA\n- Max 100 Wörter total</pre><h3>A/B-Test Prompt</h3><pre>Erstelle 2 Varianten dieser E-Mail:\n[E-Mail]\n\nVariante A: Emotionaler Ansatz\nVariante B: Fakten-basierter Ansatz\nGleicher CTA bei beiden.</pre>"}'::jsonb WHERE id = 'af06f09c-fae3-4a23-9992-9433a6c2a9e0';
