
-- Batch 2: SalesFlow, KI im Vertrieb, Automatisierung

-- Willkommen bei SalesFlow
UPDATE lessons SET meta = '{"content_html": "<h2>Willkommen bei SalesFlow</h2><h3>Was ist SalesFlow?</h3><p>SalesFlow ist deine All-in-One Plattform für KI-gestützten Vertrieb, CRM und Mitglieder-Management.</p><h3>Kernfunktionen</h3><ul><li><b>CRM & Pipeline:</b> Leads verwalten, bewerten und konvertieren</li><li><b>KI-Analyse:</b> Automatische Gesprächsanalyse und Strukturogramme</li><li><b>Angebotserstellung:</b> KI-gestützte Angebote in Minuten</li><li><b>E-Mail-Automation:</b> Sequenzen und Broadcasts</li><li><b>Academy:</b> Lernplattform für dein Team</li></ul><h3>Deine ersten Schritte</h3><ol><li>Dashboard erkunden</li><li>Profil vervollständigen</li><li>Ersten Lead anlegen</li><li>Erste KI-Analyse durchführen</li></ol>"}'::jsonb WHERE id = 'c5776330-2695-493f-a571-9784c5649861';

-- Dashboard-Navigation
UPDATE lessons SET meta = '{"content_html": "<h2>Dashboard-Navigation</h2><h3>Sidebar-Menü</h3><ul><li><b>Dashboard:</b> Überblick über KPIs und Aktivitäten</li><li><b>CRM:</b> Lead-Management und Pipeline</li><li><b>Calls:</b> Telefonate planen und analysieren</li><li><b>Angebote:</b> KI-gestützte Angebotserstellung</li><li><b>Academy:</b> Lernplattform</li><li><b>Reports:</b> Auswertungen und Analysen</li></ul><h3>Quick Actions</h3><p>Über die Quick-Action-Buttons erreichst du die häufigsten Funktionen mit einem Klick.</p><h3>Tipps</h3><ul><li>Nutze die Tastenkombination Cmd/Ctrl+K für Schnellsuche</li><li>Dein Dashboard zeigt automatisch deine wichtigsten Metriken</li><li>Benachrichtigungen erscheinen in Echtzeit</li></ul>"}'::jsonb WHERE id = '0b49f422-9ade-459d-8c93-d42d48a9e291';

-- Checkliste: Erste Schritte
UPDATE lessons SET meta = '{"content_html": "<h2>Checkliste: Erste Schritte</h2><h3>Tag 1: Setup</h3><ul><li>☐ Profil vervollständigen (Name, Firma, Telefon)</li><li>☐ Avatar hochladen</li><li>☐ E-Mail-Signatur einrichten</li></ul><h3>Tag 2: CRM kennenlernen</h3><ul><li>☐ 3 Test-Leads anlegen</li><li>☐ Pipeline-Ansicht erkunden</li><li>☐ Ersten Lead durch Pipeline bewegen</li></ul><h3>Tag 3: KI nutzen</h3><ul><li>☐ Erstes Gespräch protokollieren</li><li>☐ KI-Analyse durchführen lassen</li><li>☐ Strukturogramm-Ergebnis verstehen</li></ul><h3>Tag 4: Automatisierung</h3><ul><li>☐ Erste E-Mail-Vorlage erstellen</li><li>☐ Follow-up-Aufgabe anlegen</li><li>☐ Dashboard-Widgets anpassen</li></ul><h3>Tag 5: Vertiefung</h3><ul><li>☐ Nächsten Academy-Kurs starten</li><li>☐ KI-Angebot erstellen lassen</li><li>☐ Team-Ziel definieren</li></ul>"}'::jsonb WHERE id = 'c8ed307d-350a-42f4-b70b-4be3a9199f9a';

-- Was ist ein Lead?
UPDATE lessons SET meta = '{"content_html": "<h2>Was ist ein Lead?</h2><h3>Definition</h3><p>Ein Lead ist ein potenzieller Kunde, der Interesse an deinem Angebot gezeigt hat.</p><h3>Lead-Quellen</h3><ul><li><b>Inbound:</b> Website, Kontaktformular, Social Media</li><li><b>Outbound:</b> Kaltakquise, Prospecting, Empfehlungen</li><li><b>Automatisiert:</b> KI-Prospecting, Scraping, Partnernetzwerke</li></ul><h3>Lead-Lebenszyklus</h3><ol><li><b>Neu:</b> Lead kommt rein</li><li><b>Kontaktiert:</b> Erstansprache erfolgt</li><li><b>Qualifiziert:</b> Bedarf und Budget bestätigt</li><li><b>Angebot:</b> Proposal gesendet</li><li><b>Gewonnen/Verloren:</b> Abschluss oder Absage</li></ol><h3>KI-Prompt: Lead bewerten</h3><pre>Bewerte diesen Lead:\nName: [X]\nFirma: [Y]\nBranche: [Z]\nAnfrage: [Text]\n\nBewerte 0-100 nach: Relevanz, Budget, Timing, Entscheider.</pre>"}'::jsonb WHERE id = '1bc90100-4882-46d3-8a18-68472c748e5d';

-- Lead-Qualifizierung
UPDATE lessons SET meta = '{"content_html": "<h2>Lead-Qualifizierung mit KI</h2><h3>BANT-Methode + KI</h3><ul><li><b>B</b>udget: Hat der Lead Budget?</li><li><b>A</b>uthority: Ist er Entscheider?</li><li><b>N</b>eed: Gibt es echten Bedarf?</li><li><b>T</b>iming: Ist der Zeitpunkt richtig?</li></ul><h3>KI-Qualifizierungs-Prompt</h3><pre>Analysiere diese Lead-Anfrage:\n[Text der Anfrage]\n\nBewerte nach BANT:\n- Budget (0-25): Hinweise auf Investitionsbereitschaft?\n- Authority (0-25): Entscheider oder Informationssammler?\n- Need (0-25): Wie dringend ist das Problem?\n- Timing (0-25): Wann soll umgesetzt werden?\n\nGesamtscore: /100\nEmpfehlung: Sofort anrufen / E-Mail senden / Nurturing</pre><h3>Automatische Qualifizierung</h3><p>In SalesFlow wird jeder Lead automatisch mit einem ICP-Score bewertet. Leads über 70 Punkte erscheinen als \"Hot Leads\" in deiner Prioritätenliste.</p>"}'::jsonb WHERE id = 'a9a60a45-c416-4f0f-a572-feabb7152404';

-- ICP-Score verstehen
UPDATE lessons SET meta = '{"content_html": "<h2>ICP-Score verstehen</h2><h3>Was ist der ICP-Score?</h3><p>Der Ideal Customer Profile Score bewertet, wie gut ein Lead zu deinem idealen Kunden passt.</p><h3>Scoring-Dimensionen</h3><table><tr><th>Dimension</th><th>Gewicht</th><th>Beispiel</th></tr><tr><td>Branchenfit</td><td>30%</td><td>Handwerk, Praxis, Dienstleister</td></tr><tr><td>Unternehmensgröße</td><td>20%</td><td>10-100 Mitarbeiter optimal</td></tr><tr><td>Budget-Signale</td><td>20%</td><td>Umsatz, Investitionsbereitschaft</td></tr><tr><td>Engagement</td><td>15%</td><td>Website-Besuche, E-Mail-Öffnungen</td></tr><tr><td>Entscheider-Level</td><td>15%</td><td>GF, Inhaber, Marketing-Leiter</td></tr></table><h3>Score-Interpretation</h3><ul><li><b>80-100:</b> 🔥 Hot Lead – Sofort kontaktieren</li><li><b>60-79:</b> 🟡 Warm Lead – Zeitnah ansprechen</li><li><b>40-59:</b> 🟠 Neutral – Nurturing starten</li><li><b>0-39:</b> ❄️ Cold – Beobachten oder disqualifizieren</li></ul>"}'::jsonb WHERE id = '13cb2ef4-360d-4f68-9e0b-b7aab75017b3';

-- Der KI-gestützte Vertriebsprozess
UPDATE lessons SET meta = '{"content_html": "<h2>Der KI-gestützte Vertriebsprozess</h2><h3>Traditionell vs. KI-gestützt</h3><table><tr><th>Phase</th><th>Ohne KI</th><th>Mit KI</th></tr><tr><td>Lead-Generierung</td><td>Manuell recherchieren</td><td>KI-Prospecting automatisch</td></tr><tr><td>Qualifizierung</td><td>Bauchgefühl</td><td>Datenbasierter ICP-Score</td></tr><tr><td>Erstgespräch</td><td>Unvorbereitet</td><td>KI-briefing vorab</td></tr><tr><td>Analyse</td><td>Subjektive Notizen</td><td>KI-Transkript + Strukturogramm</td></tr><tr><td>Angebot</td><td>Stundenlange Erstellung</td><td>KI-generiert in Minuten</td></tr><tr><td>Follow-up</td><td>Vergessen / zu spät</td><td>Automatische Sequenzen</td></tr></table><h3>Dein KI-Vertriebsstack</h3><ol><li>CRM mit ICP-Scoring</li><li>KI-Gesprächsanalyse</li><li>Automatische Follow-up Pläne</li><li>KI-Angebotsgenerator</li><li>E-Mail-Automatisierung</li></ol>"}'::jsonb WHERE id = '702c49f6-ce93-45fd-993e-376838e62ab9';

-- CRM & KI
UPDATE lessons SET meta = '{"content_html": "<h2>CRM & KI: Die perfekte Kombination</h2><h3>KI-Features im CRM</h3><ul><li><b>Automatisches Scoring:</b> Jeder Lead bekommt sofort einen ICP-Score</li><li><b>Smart Suggestions:</b> KI empfiehlt die nächste beste Aktion</li><li><b>Predictive Analytics:</b> Abschlusswahrscheinlichkeit vorhersagen</li><li><b>Auto-Tagging:</b> Leads automatisch kategorisieren</li></ul><h3>Prompt: CRM-Daten analysieren</h3><pre>Analysiere diese CRM-Daten:\n[Export einfügen]\n\nIdentifiziere:\n1. Top 5 Leads nach Abschlusswahrscheinlichkeit\n2. Leads die sofort kontaktiert werden sollten\n3. Leads die mehr Nurturing brauchen\n4. Muster in erfolgreichen Abschlüssen\n\nFormat: Priorisierte Liste mit Begründung.</pre><h3>Best Practices</h3><ul><li>CRM-Daten täglich pflegen</li><li>KI-Scores wöchentlich reviewen</li><li>Scoring-Modell quartalsweise kalibrieren</li></ul>"}'::jsonb WHERE id = '5d3b538c-5766-4bf8-b96c-89c3dc4c0c11';

-- ICP-Scoring mit KI
UPDATE lessons SET meta = '{"content_html": "<h2>ICP-Scoring mit KI</h2><h3>Dein ICP definieren</h3><pre>Hilf mir mein Ideal Customer Profile zu definieren:\n\nMein Unternehmen: [X]\nMein Angebot: [Y]\nBisherige beste Kunden: [Z]\n\nErstelle ein ICP mit:\n- Branche\n- Unternehmensgröße\n- Umsatz-Range\n- Typische Schmerzpunkte\n- Entscheider-Profil\n- Budget-Erwartung\n- Kaufsignale</pre><h3>Scoring-Prompt</h3><pre>Basierend auf diesem ICP:\n[ICP einfügen]\n\nBewerte diesen Lead:\n[Lead-Daten]\n\nScore 0-100 mit Begründung pro Dimension.</pre>"}'::jsonb WHERE id = '9232f84d-cf6e-4b61-aab0-444755f7db78';

-- Arbeitsblatt: ICP definieren
UPDATE lessons SET meta = '{"content_html": "<h2>Arbeitsblatt: Dein ICP definieren</h2><h3>Schritt 1: Deine besten Kunden analysieren</h3><p>Liste deine 5 besten Kunden auf:</p><table><tr><th>Kunde</th><th>Branche</th><th>Größe</th><th>Umsatz</th><th>Warum ideal?</th></tr><tr><td>1. ___</td><td>___</td><td>___</td><td>___</td><td>___</td></tr><tr><td>2. ___</td><td>___</td><td>___</td><td>___</td><td>___</td></tr><tr><td>3. ___</td><td>___</td><td>___</td><td>___</td><td>___</td></tr></table><h3>Schritt 2: Gemeinsamkeiten finden</h3><ul><li>Branche: ___</li><li>Unternehmensgröße: ___</li><li>Typischer Schmerzpunkt: ___</li><li>Entscheider-Typ: ___</li><li>Budget-Range: ___</li></ul><h3>Schritt 3: Mit KI validieren</h3><pre>Validiere mein ICP:\n[Deine Antworten einfügen]\n\nIst dieses Profil realistisch?\nWelche Dimensionen fehlen?\nWie würdest du die Gewichtung setzen?</pre>"}'::jsonb WHERE id = 'f54f0b47-9f23-47fc-9cab-7a1780f333a0';

-- Quiz: Lead-Qualifizierung
UPDATE lessons SET meta = '{"content_html": "<h2>Quiz: Lead-Qualifizierung</h2><h3>Frage 1</h3><p>Wofür steht BANT?</p><ul><li>a) Budget, Authority, Need, Timing ✅</li><li>b) Brand, Audience, Network, Technology</li><li>c) Business, Analytics, Numbers, Targets</li></ul><h3>Frage 2</h3><p>Ein Lead hat ICP-Score 85. Was tust du?</p><ul><li>a) In die Nurturing-Liste</li><li>b) Sofort persönlich kontaktieren ✅</li><li>c) Automatische E-Mail senden</li></ul><h3>Frage 3</h3><p>Was ist der wichtigste Vorteil von KI-Scoring?</p><ul><li>a) Es ist billiger</li><li>b) Es ist objektiv und konsistent ✅</li><li>c) Es braucht keine Daten</li></ul><h3>Frage 4</h3><p>Wann solltest du dein Scoring-Modell kalibrieren?</p><ul><li>a) Nie, es lernt selbst</li><li>b) Quartalsweise anhand realer Abschlüsse ✅</li><li>c) Nur bei Beschwerden</li></ul>"}'::jsonb WHERE id = '2f1ee1b9-1b56-4766-851c-5e56654f0db6';

-- Was ist No-Code Automation?
UPDATE lessons SET meta = '{"content_html": "<h2>Was ist No-Code Automation?</h2><h3>Definition</h3><p>No-Code Automation ermöglicht dir, Geschäftsprozesse zu automatisieren – ohne eine Zeile Code zu schreiben.</p><h3>Die 3 Säulen</h3><ol><li><b>Trigger:</b> Was löst den Workflow aus? (z.B. neuer Lead, E-Mail, Zeitplan)</li><li><b>Aktion:</b> Was soll passieren? (z.B. E-Mail senden, CRM updaten)</li><li><b>KI-Modul:</b> Intelligente Entscheidungen treffen (z.B. Lead bewerten, Text generieren)</li></ol><h3>Typische Automationen</h3><ul><li>Lead kommt rein → KI bewertet → Vertrieb wird benachrichtigt</li><li>Angebot erstellt → Follow-up E-Mail nach 3 Tagen</li><li>Gespräch beendet → Transkript → KI-Analyse → Aufgabe erstellt</li><li>Wöchentlicher KPI-Report → KI-Zusammenfassung → Slack-Nachricht</li></ul>"}'::jsonb WHERE id = 'b5824d60-f810-4e82-8fd3-2a45d2274605';

-- Make vs. Zapier vs. n8n
UPDATE lessons SET meta = '{"content_html": "<h2>Make vs. Zapier vs. n8n</h2><h3>Vergleich</h3><table><tr><th>Feature</th><th>Make</th><th>Zapier</th><th>n8n</th></tr><tr><td>Bedienung</td><td>Mittel</td><td>Einfach</td><td>Komplex</td></tr><tr><td>KI-Module</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td></tr><tr><td>Preis</td><td>Ab 9€</td><td>Ab 19$</td><td>Kostenlos*</td></tr><tr><td>Apps</td><td>1500+</td><td>6000+</td><td>400+</td></tr><tr><td>Hosting</td><td>Cloud</td><td>Cloud</td><td>Self-hosted</td></tr></table><h3>Empfehlung</h3><ul><li><b>Einsteiger:</b> Zapier – einfachste Bedienung</li><li><b>Power-User:</b> Make – bestes Preis-Leistungs-Verhältnis</li><li><b>Entwickler:</b> n8n – maximale Kontrolle</li></ul><h3>Prompt: Tool-Entscheidung</h3><pre>Ich möchte [Prozess] automatisieren.\nTeamgröße: [X]\nBudget: [Y]/Monat\nTechnisches Level: [Anfänger/Fortgeschritten]\n\nWelches Tool empfiehlst du und warum?</pre>"}'::jsonb WHERE id = '6498fce3-ec67-442c-97bb-628fe13efa93';

-- Workflow: Lead → E-Mail → CRM
UPDATE lessons SET meta = '{"content_html": "<h2>Workflow: Lead → E-Mail → CRM</h2><h3>Der komplette Automatisierungs-Flow</h3><ol><li><b>Trigger:</b> Kontaktformular wird ausgefüllt</li><li><b>Schritt 1:</b> Lead-Daten in CRM speichern</li><li><b>Schritt 2:</b> KI bewertet den Lead (ICP-Score)</li><li><b>Schritt 3:</b> Router basierend auf Score<ul><li>Score > 70: Slack-Alert an Vertrieb + Sofort-E-Mail mit Terminbuchung</li><li>Score 40-70: Nurturing-E-Mail-Sequenz starten</li><li>Score < 40: In Beobachtungsliste</li></ul></li><li><b>Schritt 4:</b> Aufgabe für zuständigen Mitarbeiter erstellen</li></ol><h3>KI-Prompt im Workflow</h3><pre>System: Du bist ein Lead-Scoring-System für [Firma].\nBewerte anhand des ICP: [ICP-Definition]\n\nInput: {{lead_data}}\n\nOutput (nur JSON):\n{\n  \"score\": 0-100,\n  \"priority\": \"hot/warm/cold\",\n  \"reason\": \"Kurze Begründung\",\n  \"next_action\": \"Empfohlene nächste Aktion\"\n}</pre>"}'::jsonb WHERE id = 'fa3cec47-1bcd-43ab-8c6e-3e248179434f';

-- Praxis: Eigenen Workflow bauen
UPDATE lessons SET meta = '{"content_html": "<h2>Praxis: Eigenen Workflow bauen</h2><h3>Aufgabe: Lead-Benachrichtigungs-Workflow</h3><p>Baue einen Workflow der bei neuen Leads automatisch:</p><ol><li>Den Lead mit KI bewertet</li><li>Eine personalisierte Willkommens-E-Mail sendet</li><li>Bei Hot Leads den Vertrieb per Slack benachrichtigt</li></ol><h3>Schritt-für-Schritt</h3><ol><li>Erstelle einen Webhook-Trigger</li><li>Füge ein OpenAI-Modul hinzu</li><li>Konfiguriere den Scoring-Prompt</li><li>Füge einen Router mit 2 Pfaden hinzu</li><li>Verbinde E-Mail- und Slack-Module</li><li>Teste mit echten Lead-Daten</li></ol><h3>Bonus-Aufgabe</h3><p>Erweitere den Workflow um eine automatische Aufgaben-Erstellung im CRM.</p>"}'::jsonb WHERE id = '80268367-b2ee-4672-ba9e-82ad5df23b9c';
