
-- Add new prompt-template and guide lessons to existing modules

-- Prompting Grundlagen - "Was ist KI?" module (aa110000-0000-0000-0000-000000000001)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('aa110000-0000-0000-0000-000000000001', 'Prompt-Cheatsheet: Deine ersten 10 Prompts', 'Die 10 wichtigsten Prompts für den Einstieg – copy & paste ready.', 'worksheet', 3, 600, '{"content_html": "<h2>Deine ersten 10 Prompts</h2><h3>1. E-Mail zusammenfassen</h3><pre>Fasse diese E-Mail in 3 Bullet Points zusammen:\n[E-Mail einfügen]</pre><h3>2. Antwort formulieren</h3><pre>Schreibe eine professionelle Antwort auf:\n[E-Mail]\nTon: freundlich, lösungsorientiert</pre><h3>3. Meeting vorbereiten</h3><pre>Ich habe ein Meeting mit [Person/Firma] zum Thema [X].\nErstelle:\n- 5 Gesprächspunkte\n- 3 mögliche Einwände\n- Ideales Ergebnis</pre><h3>4. Texte verbessern</h3><pre>Verbessere diesen Text:\n[Text]\nMache ihn: kürzer, klarer, überzeugender</pre><h3>5. Ideen brainstormen</h3><pre>Gib mir 10 kreative Ideen für [Thema].\nZielgruppe: [X]\nZiel: [Y]</pre><h3>6. Social Media Post</h3><pre>Schreibe einen LinkedIn-Post über [Thema].\nMax 200 Wörter, mit Hook und CTA.</pre><h3>7. Aufgabenliste erstellen</h3><pre>Erstelle eine priorisierte To-Do-Liste für [Projekt].\nSortiere nach: Dringend > Wichtig > Nice-to-have</pre><h3>8. Feedback geben</h3><pre>Formuliere konstruktives Feedback zu:\n[Situation]\nMethode: Sandwich (Lob-Kritik-Lob)</pre><h3>9. Wettbewerber analysieren</h3><pre>Analysiere [Wettbewerber]:\n- Stärken und Schwächen\n- Differenzierungsmöglichkeiten\n- Unsere Vorteile</pre><h3>10. Entscheidung treffen</h3><pre>Hilf mir bei der Entscheidung:\nOption A: [X]\nOption B: [Y]\nKriterien: [Kosten, Zeit, Qualität]\nErstelle Pro/Contra-Tabelle</pre>"}'),

('aa110000-0000-0000-0000-000000000001', 'KI-Glossar: Begriffe die du kennen musst', 'Von API bis Zero-Shot: Die wichtigsten KI-Begriffe erklärt.', 'worksheet', 4, 480, '{"content_html": "<h2>KI-Glossar für Business</h2><dl><dt><b>LLM (Large Language Model)</b></dt><dd>KI-Modell, das auf riesigen Textmengen trainiert wurde (z.B. GPT, Claude, Gemini)</dd><dt><b>Prompt</b></dt><dd>Die Anweisung/Frage, die du an die KI gibst</dd><dt><b>Token</b></dt><dd>Kleinste Texteinheit (~4 Zeichen). Bestimmt Kosten und Kontextlänge</dd><dt><b>Kontext-Fenster</b></dt><dd>Wie viel Text die KI gleichzeitig verarbeiten kann (z.B. 128K Token)</dd><dt><b>Halluzination</b></dt><dd>Wenn die KI überzeugend klingende, aber falsche Infos generiert</dd><dt><b>Fine-Tuning</b></dt><dd>Nachtraining eines Modells auf eigene Daten</dd><dt><b>RAG (Retrieval-Augmented Generation)</b></dt><dd>KI sucht erst in deinen Dokumenten, dann antwortet sie</dd><dt><b>Zero-Shot</b></dt><dd>Prompt ohne Beispiele</dd><dt><b>Few-Shot</b></dt><dd>Prompt mit 2-3 Beispielen für bessere Ergebnisse</dd><dt><b>Temperature</b></dt><dd>Kreativitäts-Regler (0 = exakt, 1 = kreativ)</dd><dt><b>System Prompt</b></dt><dd>Versteckte Anweisung, die das Verhalten der KI grundlegend steuert</dd><dt><b>API</b></dt><dd>Schnittstelle um KI-Modelle programmatisch anzusprechen</dd></dl>"}');

-- "Dein erster Prompt" module (aa110000-0000-0000-0000-000000000002)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('aa110000-0000-0000-0000-000000000002', 'Prompt-Fehler die jeder macht', 'Die 7 häufigsten Prompt-Fehler und wie du sie vermeidest.', 'video', 3, 720, '{"content_html": "<h2>7 Prompt-Fehler vermeiden</h2><h3>1. Zu vage</h3><p>❌ Schreib mir was über Marketing<br/>✅ Schreibe 5 LinkedIn-Post-Ideen für B2B-Handwerksbetriebe zum Thema Mitarbeitergewinnung</p><h3>2. Keine Rolle definiert</h3><p>❌ Hilf mir beim Verkaufen<br/>✅ Du bist ein erfahrener B2B-Vertriebstrainer. Hilf mir...</p><h3>3. Kein Format vorgeben</h3><p>❌ Erstelle einen Plan<br/>✅ Erstelle einen Plan als Tabelle mit: Datum | Aufgabe | Verantwortlich | Status</p><h3>4. Alles auf einmal fragen</h3><p>Teile komplexe Aufgaben in Schritte auf.</p><h3>5. Kontext vergessen</h3><p>Gib immer Hintergrund: Branche, Zielgruppe, Ziel.</p><h3>6. Nicht iterieren</h3><p>Verfeinere die Antwort: Mach es kürzer / Ändere den Ton / Füge Beispiele hinzu</p><h3>7. Output nicht prüfen</h3><p>KI-Ausgaben immer auf Fakten und Relevanz prüfen!</p>"}'),

('aa110000-0000-0000-0000-000000000002', 'Übung: Prompt-Verbesserung', 'Verbessere 5 schlechte Prompts zu professionellen Anweisungen.', 'task', 4, 900, '{"content_html": "<h2>Übung: Prompts verbessern</h2><p>Verbessere diese 5 Prompts:</p><h3>1. Original:</h3><pre>Schreib eine E-Mail</pre><p>Deine verbesserte Version: ___</p><h3>2. Original:</h3><pre>Mach mir einen Social Media Plan</pre><p>Deine verbesserte Version: ___</p><h3>3. Original:</h3><pre>Analysiere meinen Kunden</pre><p>Deine verbesserte Version: ___</p><h3>4. Original:</h3><pre>Erstelle ein Angebot</pre><p>Deine verbesserte Version: ___</p><h3>5. Original:</h3><pre>Hilf mir beim Verkaufen</pre><p>Deine verbesserte Version: ___</p><p><b>Tipp:</b> Nutze RACE oder CRISP für jede Verbesserung!</p>"}');

-- Chain-of-Thought module (d47df076-4075-4d08-b44e-6159ecc6d143)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('d47df076-4075-4d08-b44e-6159ecc6d143', 'Prompt-Vorlagen: Vertriebsanalyse', 'Copy & Paste Prompts für Gesprächsanalyse und Einwandbehandlung.', 'worksheet', 3, 600, '{"content_html": "<h2>Vertriebsanalyse-Prompts</h2><h3>Gesprächsanalyse</h3><pre>Analysiere dieses Verkaufsgespräch:\n[Transkript]\n\nBewerte:\n1. Rapport-Aufbau (1-10)\n2. Bedarfsermittlung (1-10)\n3. Einwandbehandlung (1-10)\n4. Abschlusstechnik (1-10)\n\nGib 3 konkrete Verbesserungsvorschläge.</pre><h3>Einwandbehandlung</h3><pre>Kunde sagt: [Einwand]\nKontext: [Produkt/Situation]\n\nGib 3 verschiedene Antworten:\n1. Empathisch (Verständnis zeigen)\n2. Logisch (mit Zahlen/Fakten)\n3. Storytelling (mit Beispiel/Case Study)</pre><h3>Gesprächsvorbereitung</h3><pre>Bereite mich auf ein Gespräch vor:\nKunde: [Name, Firma, Branche]\nAnlass: [Erstgespräch/Follow-up/Closing]\nZiel: [Was will ich erreichen?]\n\nErstelle:\n- 5 Einstiegsfragen\n- 3 mögliche Einwände + Antworten\n- Ideale Abschluss-Formulierung</pre>"}');

-- KI-Tools im Überblick module (aa110000-0000-0000-0000-000000000004)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('aa110000-0000-0000-0000-000000000004', 'Tool-Guide: ChatGPT, Claude, Gemini im Vergleich', 'Welches Tool für welchen Zweck? Dein Entscheidungs-Guide.', 'worksheet', 3, 600, '{"content_html": "<h2>KI-Tool Entscheidungs-Guide</h2><table><tr><th>Kriterium</th><th>ChatGPT</th><th>Claude</th><th>Gemini</th></tr><tr><td>Texterstellung</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td></tr><tr><td>Analyse</td><td>⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td></tr><tr><td>Coding</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td></tr><tr><td>Kreativität</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td></tr><tr><td>Lange Dokumente</td><td>⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td></tr><tr><td>Bildverarbeitung</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐⭐⭐</td><td>⭐⭐⭐⭐⭐</td></tr><tr><td>Preis</td><td>20$/Mo</td><td>20$/Mo</td><td>20$/Mo</td></tr></table><h3>Empfehlung</h3><ul><li><b>Vertrieb:</b> ChatGPT oder Claude</li><li><b>Analyse:</b> Claude oder Gemini</li><li><b>Content:</b> ChatGPT</li><li><b>Coding:</b> Claude oder ChatGPT</li></ul>"}');

-- Content-Kalender module (d98878b0-e44c-453c-8d85-00815e69b2f5)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('d98878b0-e44c-453c-8d85-00815e69b2f5', 'Prompt-Vorlagen: Social Media Content', '15 sofort einsetzbare Prompts für LinkedIn, Instagram und Newsletter.', 'worksheet', 3, 600, '{"content_html": "<h2>15 Social Media Prompts</h2><h3>LinkedIn</h3><pre>1. Thought-Leadership Post:\nSchreibe einen LinkedIn-Post der meine Expertise in [Thema] zeigt.\nErstzeile: Provokante These.\nStruktur: These → Story → 3 Learnings → Frage an Community</pre><pre>2. Case-Study Post:\nKunde: [Name/Branche]\nProblem: [X]\nLösung: [Y]\nErgebnis: [Z]\nFormat: Vorher/Nachher mit konkreten Zahlen</pre><pre>3. Karussell-Konzept:\nThema: [X]\nErstelle 8 Slides:\nSlide 1: Hook\nSlide 2-7: Inhalte\nSlide 8: CTA</pre><h3>Instagram</h3><pre>4. Reel-Skript:\nThema: [X]\nDauer: 30 Sekunden\nHook (3 Sek) → Problem (5 Sek) → Lösung (15 Sek) → CTA (7 Sek)</pre><pre>5. Story-Sequenz:\n5 Stories zum Thema [X]\nStory 1: Frage/Umfrage\nStory 2-4: Tipps\nStory 5: CTA mit Link</pre><h3>Newsletter</h3><pre>6. Newsletter-Vorlage:\nBetreff: [A/B Variante]\nPreview: Max 40 Zeichen\nIntro: Persönlich\nHauptteil: 3 Insights\nCTA: Eine klare Handlung</pre>"}');

-- E-Mail-Sequenzen module (6739b1ef-dfc8-45dd-8360-a20d41d5af69)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('6739b1ef-dfc8-45dd-8360-a20d41d5af69', 'Prompt-Vorlagen: E-Mail-Sequenzen', 'Komplette E-Mail-Sequenz Prompts für Lead-Nurturing und Follow-ups.', 'worksheet', 3, 720, '{"content_html": "<h2>E-Mail-Sequenz Prompts</h2><h3>5-teilige Lead-Nurturing Sequenz</h3><pre>Erstelle eine 5-teilige E-Mail-Sequenz:\n\nZielgruppe: [ICP]\nZiel: Von Erstkontakt zum Termin\n\nE-Mail 1 (Tag 0): Willkommen + Quick Win\nE-Mail 2 (Tag 3): Schmerzpunkt adressieren\nE-Mail 3 (Tag 7): Case Study / Social Proof\nE-Mail 4 (Tag 14): Exklusives Angebot\nE-Mail 5 (Tag 21): Last Chance + FOMO\n\nPro E-Mail: Betreff, Preheader, Body (max 150 Wörter), CTA</pre><h3>Follow-up nach Angebot</h3><pre>Schreibe eine Follow-up E-Mail:\nAngebot: [Produkt/Service]\nGesendet vor: [X Tagen]\nKein Feedback bisher.\nTon: Nicht pushy, Mehrwert bieten.\nInkl. Social Proof oder neuen Insight.</pre><h3>Re-Engagement</h3><pre>Schreibe eine Re-Engagement E-Mail an Kontakte die seit 90 Tagen inaktiv sind.\nBetreff: Neugier wecken\nBody: Kurz, persönlich, neuer Mehrwert\nCTA: Einfache Ja/Nein Frage</pre>"}');

-- KI im Vertrieb module (aa110000-0000-0000-0000-000000000007)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('aa110000-0000-0000-0000-000000000007', 'Prompt-Vorlagen: Vertriebsprozess', '10 Prompts für jeden Schritt im Sales Funnel.', 'worksheet', 3, 720, '{"content_html": "<h2>Sales Funnel Prompts</h2><h3>1. Prospecting</h3><pre>Recherchiere [Firma/Branche]:\n- Unternehmensgröße und Umsatz\n- Aktuelle Herausforderungen\n- Entscheidungsträger\n- Anknüpfungspunkte für unser Angebot</pre><h3>2. Erstansprache</h3><pre>Schreibe eine Kaltakquise-Nachricht:\nKanal: [E-Mail/LinkedIn/Telefon]\nEmpfänger: [Titel, Branche]\nUnser Angebot: [X]\nHook: Bezug auf aktuelle Branchenentwicklung</pre><h3>3. Discovery Call Vorbereitung</h3><pre>Erstelle Fragebogen für Discovery Call:\nBranche: [X]\nProdukt: [Y]\n10 offene Fragen nach SPIN-Methode:\n- Situation (2)\n- Problem (3)\n- Implikation (3)\n- Need-Payoff (2)</pre><h3>4. Angebotserstellung</h3><pre>Erstelle Angebotstext:\nKunde: [Infos]\nBedarf: [aus Discovery Call]\nLösung: [unser Angebot]\nFormat: Problem → Lösung → Nutzen → Investition → Nächste Schritte</pre><h3>5. Closing-Vorbereitung</h3><pre>Der Kunde hat folgende Bedenken: [X]\nErstelle 3 Closing-Strategien:\n1. Assumptive Close\n2. Alternative Close\n3. Urgency Close\nMit konkreten Formulierungen.</pre>"}');

-- No-Code Automation module (aa110000-0000-0000-0000-000000000009)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('aa110000-0000-0000-0000-000000000009', 'Anleitung: Dein erster Make.com Workflow', 'Schritt-für-Schritt Anleitung für deinen ersten KI-Workflow.', 'worksheet', 3, 900, '{"content_html": "<h2>Make.com KI-Workflow Anleitung</h2><h3>Schritt 1: Account erstellen</h3><p>Gehe zu make.com und erstelle einen kostenlosen Account.</p><h3>Schritt 2: Neues Szenario</h3><ol><li>Klicke Neues Szenario</li><li>Wähle Trigger: Webhook (empfohlen für CRM)</li></ol><h3>Schritt 3: KI-Modul hinzufügen</h3><ol><li>Suche OpenAI oder HTTP-Modul</li><li>Verbinde deinen API-Key</li><li>Konfiguriere den Prompt:</li></ol><pre>System: Du bist ein Lead-Scoring-Assistent.\nUser: Bewerte: {{1.lead_name}} aus {{1.branche}}\nAntwort als JSON: {score: 0-100, action: text}</pre><h3>Schritt 4: Router</h3><ul><li>Score > 70 → Pfad 1: Slack Notification</li><li>Score 40-70 → Pfad 2: E-Mail-Sequenz starten</li><li>Score < 40 → Pfad 3: In Nurturing-Liste</li></ul><h3>Schritt 5: Testen</h3><p>Sende Test-Daten und prüfe alle Pfade.</p>"}');

-- Custom GPTs module (d7f5f035-1467-49f3-810f-2d182186789b)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('d7f5f035-1467-49f3-810f-2d182186789b', 'Anleitung: Eigenen Sales-GPT bauen', 'Schritt-für-Schritt: Deinen persönlichen Vertriebs-Assistenten erstellen.', 'worksheet', 3, 900, '{"content_html": "<h2>Deinen Sales-GPT bauen</h2><h3>1. GPT Builder öffnen</h3><p>ChatGPT → Explore GPTs → Create a GPT</p><h3>2. Instructions schreiben</h3><pre>Du bist der Sales-Assistent für [Firma].\n\nDeine Aufgaben:\n- Leads bewerten und priorisieren\n- E-Mails formulieren\n- Einwände entkräften\n- Angebote vorbereiten\n\nDu kennst:\n- Unsere Produkte: [Liste]\n- Unsere Zielgruppe: [ICP]\n- Unsere Preise: [Preisstruktur]\n- Unsere USPs: [3-5 Punkte]\n\nDu antwortest immer:\n- Praxisorientiert mit konkreten Formulierungen\n- Im Ton unserer Marke: [Beschreibung]\n- Mit konkreten nächsten Schritten</pre><h3>3. Knowledge hochladen</h3><ul><li>Produktkatalog (PDF)</li><li>Preisliste</li><li>Case Studies</li><li>FAQ-Dokument</li><li>Einwandbehandlungs-Guide</li></ul><h3>4. Conversation Starters</h3><pre>- Bereite mich auf ein Gespräch mit [Firma] vor\n- Bewerte diesen Lead: [Daten]\n- Formuliere ein Angebot für [Bedarf]\n- Wie reagiere ich auf den Einwand: [X]</pre>"}');

-- Strukturogramm module (819a35c5-ff26-47f3-8c0a-422b1168452a)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('819a35c5-ff26-47f3-8c0a-422b1168452a', 'Prompt-Vorlagen: Strukturogramm-Analyse', 'KI-Prompts zur Identifizierung von Kommunikationstypen.', 'worksheet', 3, 720, '{"content_html": "<h2>Strukturogramm-Analyse Prompts</h2><h3>Typ-Erkennung aus Gespräch</h3><pre>Analysiere dieses Gesprächstranskript:\n[Transkript]\n\nIdentifiziere den Strukturogramm-Typ:\n- Grünhirn (beziehungsorientiert, harmoniebedürftig)\n- Rothirn (dominant, ergebnisorientiert)\n- Blauhirn (analytisch, detailorientiert)\n\nBegründe deine Einschätzung mit 3 konkreten Beispielen aus dem Gespräch.\n\nEmpfehle die optimale Kommunikationsstrategie.</pre><h3>Typ-spezifische Ansprache</h3><pre>Mein Kunde ist ein [Typ].\nIch möchte: [Ziel]\n\nFormuliere:\n1. Passende Eröffnung\n2. Argumentationsstruktur\n3. Einwandbehandlung\n4. Abschluss-Formulierung\n\nAlles angepasst an den Kommunikationstyp.</pre><h3>Typ-Erkennung aus E-Mail</h3><pre>Welcher Typ hat diese E-Mail geschrieben?\n[E-Mail]\n\nAnalysiere: Wortwahl, Länge, Struktur, Emotionalität.\nGib Typ + Begründung + Antwort-Empfehlung.</pre>"}');

-- Angebote mit KI module (37d043c2-43d7-4a7e-8e65-6d1cc630a3c1)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('37d043c2-43d7-4a7e-8e65-6d1cc630a3c1', 'Prompt-Vorlagen: Angebotserstellung', 'Professionelle Angebote in Minuten mit KI erstellen.', 'worksheet', 3, 720, '{"content_html": "<h2>KI-Angebotserstellung</h2><h3>Komplett-Angebot</h3><pre>Erstelle ein professionelles Angebot:\n\nKunde: [Name, Firma]\nBranche: [X]\nBedarf: [aus Discovery Call]\nBudget-Range: [X-Y EUR]\n\nStruktur:\n1. Persönliche Anrede mit Bezug aufs Gespräch\n2. Problem-Zusammenfassung (Schmerzpunkte)\n3. Unsere Lösung (Module/Leistungen)\n4. Erwartete Ergebnisse (konkret, messbar)\n5. Investition (3 Preis-Optionen)\n6. Zeitplan\n7. Nächste Schritte\n8. Garantie\n\nTon: Professionell, empathisch, nicht werblich.</pre><h3>Preis-Argumentation</h3><pre>Kunde: [Branche, Größe]\nPreis: [X EUR]\nROI-Berechnung:\n- Aktuelle Kosten: [manueller Aufwand in Stunden * Stundensatz]\n- Mit unserer Lösung: [Zeitersparnis]\n- Amortisation: [Zeitraum]\nFormuliere die Argumentation so, dass der Preis als Investment verstanden wird.</pre>"}');

-- KI-Agenten module (88db7fc5-fd3e-455b-85b1-b890f0970797)
INSERT INTO lessons (module_id, name, description, lesson_type, sort_order, duration_seconds, meta) VALUES
('88db7fc5-fd3e-455b-85b1-b890f0970797', 'Anleitung: KI-Agent für Lead-Qualifizierung', 'Baue einen autonomen KI-Agenten der Leads bewertet und Follow-ups plant.', 'worksheet', 3, 1200, '{"content_html": "<h2>KI-Agent: Lead-Qualifizierung</h2><h3>Architektur</h3><pre>Input: Neue Leads aus CRM\n↓\nAgent 1: Firmendaten recherchieren\n↓\nAgent 2: ICP-Fit bewerten\n↓\nAgent 3: Kommunikationsstrategie vorschlagen\n↓\nOutput: Priorisierte Liste + Handlungsempfehlungen</pre><h3>System Prompt für Agent</h3><pre>Du bist ein Lead-Qualifizierungs-Agent.\n\nDeine Aufgaben:\n1. Bewerte jeden Lead anhand des ICP\n2. Recherchiere Firmendaten\n3. Berechne einen Score (0-100)\n4. Empfehle nächste Aktion\n\nICP-Kriterien:\n- Branche: [erlaubt: X, Y, Z]\n- Größe: [min: 10, optimal: 20-100 MA]\n- Umsatz: [min: 500K EUR]\n- Region: [DACH]\n\nAntworte IMMER als JSON:\n{\n  \"score\": number,\n  \"priority\": \"hot|warm|cold\",\n  \"reasoning\": \"string\",\n  \"next_action\": \"string\",\n  \"talking_points\": [\"string\"]\n}</pre>"}');
