// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pabcpsjszybdujlfzfvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYmNwc2pzenliZHVqbGZ6ZnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MjEyMjMsImV4cCI6MjA4NTk5NzIyM30.zOlLQQGRaXmprmHR0r3OzjCpiZJXcKLMVgAT0FjwrYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});